### ISSUE TITLE
Cable for Stramatel remote

### ISSUE THREAD

**Issue by Ady-C** [tomkohler/Panel2Net#3]
Hello,

Can you advise regarding the cable used for Stramatel remotes? I need the 5Din male - DB9 female cable and I don't know the connections I need to use. I think that for the 5DIN I will use 1 for ground 2 for Tx+ and 4 for Tx- but I didn't found the specific RS485 pinout that Stramatel is using.

Thank you,

**Comment by tomkohler** [comment]
Hi,

here's the document that explains the protocols and the pin setting for the
cables. Just go to the stramatel section.
Is that answering your question?

Please note that I have written the doc in 2017 and made some custom cables
at the same time;
hence I don't know if there are new versions of the panel and software that
could make this data obsolete.

Best regards

Thomas

**Comment by Ady-C** [comment]
Ok thank you.

**Comment by Beastlybear2017** [comment]
Hello, just wondering if you had any luck with this?

I am currently using Scoreboard OCR, however would love to be able to move away from OCR methods. Any information that you may have found / learned would be greatly appreciated if you were able to get this working :)

**Comment by tomkohler** [comment]
Hi,

I ran this by directly plug into the consoles making the cables and
decoding the data streams in the setup I described. This setup worked few
years ago with Swiss Basketball for over 500 games.
Now the consoles might have evolved, as I did that besides my dayjob as a
volunteer, I have not invested time in maintaining the solution or code.

Hope that helps.

TK

**Comment by Ady-C** [comment]
![2](https://github.com/user-attachments/assets/1b38a4bb-b7e8-48f4-8d38-4463ed6d35a2)
![3](https://github.com/user-attachments/assets/9d737cf8-2769-4da0-a035-08eb0e9d2ebb)
![4](https://github.com/user-attachments/assets/46206f2e-aefd-46fe-a907-48894a9feef1)


This is how I've made cable from stramatel remote to Moxa. It works I've been using it for more than 1 year.

**Comment by mar1ged** [comment]
@Ady-C Thanks a lot for sharing this Updates information. Did you notice any changes in protocol? The Stramatel device I'm using seems to send using a different protocol.
Would you mind sharing the model information of yours ?
